[package]
name = "flux-sys"
version = "0.1.0"
authors = ["Tom Scogland <scogland1@llnl.gov>"]
edition = "2018"
links = "flux-core"

[dependencies]

[build-dependencies]
which = "2.0.1"
bindgen = "^0.65.1"
